site_name: "Open Observability"

theme:
  name: material
  custom_dir: docs/overrides
  logo: img/logo_o11y_black.png
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - content.action.edit
    - content.action.view
    - navigation.footer
    - navigation.instant
    - navigation.path
    - navigation.top
    - toc.follow

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes

extra_css:
  - "styles/extra.css"
  - "styles/table.css"

repo_url: https://github.com/liatrio/openo11y.dev

nav:
  - "Welcome to Open O11y": "index.md"
  - "Guidance":
      - "Leading Delivery Metrics": "./delivery-metrics.md"
  - "O11y Quick Start Platform":
      - "Overview": "./platform/README.md"
      - "Architecture": "./platform/architecture.md"
      - "Getting Started":
          - "AWS": "./platform/aws.md"
  - "Contributing": "./contributing.md"
