site_name: "Open Observability"

theme:
  name: material
  custom_dir: docs/overrides
  logo: img/logo_o11y_black.png
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - content.action.edit
    - content.action.view
    - navigation.footer
    - navigation.instant
    - navigation.path
    - navigation.top
    - toc.follow

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format:
            !!python/object/apply:pymdownx.arithmatex.arithmatex_fenced_format {
              which: generic,
            }
  - footnotes

extra_css:
  - "styles/extra.css"
  - "styles/table.css"

repo_url: https://github.com/liatrio/openo11y.dev

nav:
  - "Welcome to Open O11y": "index.md"
  - "Guidance":
      - "Why Metrics Matter": "./guidance/why-metrics-matter.md"
      # - "Who Should Use Metrics": "./guidance/using-metrics-effectively.md"
      - "Delivery Metrics":
          - "Overview": "./guidance/metrics/overview.md"
          - "Lagging Inidicators": "./guidance/metrics/lagging-delivery-indicators.md"
          - "Leading Inidicators": "./guidance/metrics/leading-delivery-indicators.md"
          - "DevEx & Platform": "./guidance/metrics/devex-platform.md"
          - "Satisfaction & Well-Being": "./guidance/metrics/satisfaction-well-being.md"
  # - "O11y Quick Start Platform":
  #     - "Overview": "./platform/README.md"
  #     - "Architecture": "./platform/architecture.md"
  #     - "Recommended Implementations":
  #         - "AWS": "./platform/aws.md"
  - "Contributing": "./contributing.md"
