site_name: "Open Observability"

theme:
  name: material
  custom_dir: docs/overrides
  logo: img/logo_o11y_black.png
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - content.action.edit
    - content.action.view
    - navigation.footer
    - navigation.instant
    - navigation.path
    - navigation.top
    - toc.follow

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format:
            !!python/object/apply:pymdownx.arithmatex.arithmatex_fenced_format {
              which: generic,
            }
  - footnotes

extra_css:
  - "styles/extra.css"
  - "styles/table.css"

repo_url: https://github.com/liatrio/openo11y.dev

nav:
  - "Welcome to OpenO11y": "index.md"
  - "Why Metrics Matter": "./why-metrics-matter.md"
  - "Guidance":
    - "Human Systems":
        - "Observing Human Systems": "./human-systems/observing-human-systems.md"
        - "Delivery Metrics":
            - "Overview": "./human-systems/delivery-metrics/overview.md"
            - "Lagging Inidicators": "./human-systems/delivery-metrics/lagging-delivery-indicators.md"
            - "Leading Inidicators": "./human-systems/delivery-metrics/leading-delivery-indicators.md"
            - "DevEx & Platform": "./human-systems/delivery-metrics/devex-platform.md"
            - "Satisfaction & Well-Being": "./human-systems/delivery-metrics/satisfaction-well-being.md"
    - "Business Systems": "./business-systems.md"
  - "Demos":
    - "Delivery Metrics Demo": "./delivery-demo.md"
  # - "O11y Quick Start Platform":
  #     - "Overview": "./platform/README.md"
  #     - "Architecture": "./platform/architecture.md"
  #     - "Recommended Implementations":
  #         - "AWS": "./platform/aws.md"
  - "External Resources": "./useful-resources.md"
  - "Contributing": "./contributing.md"
